name: cat_aloge
description: "A Flutter app that detects and organizes cat photos"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Core
  cupertino_icons: ^1.0.8

  # State Management
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3

  # Navigation
  go_router: ^16.2.0

  # UI & Theming
  flutter_screenutil: ^5.9.0
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0

  # Permissions & File Access
  permission_handler: ^12.0.1
  photo_manager: ^3.0.0

  # AI/ML - Cat Detection
  tflite_flutter: ^0.11.0 # Note: Ensure you follow setup for this package
  image: ^4.1.6

  # Local Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.2

  # Sharing & Utils
  share_plus: ^11.1.0
  uuid: ^4.3.3

  # HTTP & JSON
  dio: ^5.4.1
  json_annotation: ^4.8.1

  # Logging
  logger: ^2.0.2+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

  # Code Generation
  build_runner: ^2.4.7
  riverpod_generator: ^2.3.9
  json_serializable: ^6.7.1
  hive_generator: ^2.0.1

  # Testing
  mockito: ^5.4.4
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/models/cat_detection_model.tflite
    - assets/ml/