// Mocks generated by Mockito 5.4.4 from annotations
// in cat_aloge/test/features/favorites/presentation/views/favorites_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:cat_aloge/features/favorites/domain/usecases/get_favorites.dart'
    as _i2;
import 'package:cat_aloge/features/gallery/domain/entities/cat_photo.dart'
    as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [GetFavorites].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetFavorites extends _i1.Mock implements _i2.GetFavorites {
  MockGetFavorites() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.CatPhoto>> call() => (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
        ),
        returnValue: _i3.Future<List<_i4.CatPhoto>>.value(<_i4.CatPhoto>[]),
      ) as _i3.Future<List<_i4.CatPhoto>>);
}
